name: Create PR on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create a new branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git checkout -b issue-${{ github.event.issue.number }}
          git pull origin main

      - name: Make a change
        run: |
          echo "Issue #${{ github.event.issue.number }} - $(date)" >> deployments.txt
          git add deployments.txt
          git status
          git diff --cached
          git commit -m "Update deployments.txt for issue #${{ github.event.issue.number }} on $(date)" || echo "No changes to commit"
          git log -1

      - name: Push branch
        run: |
          git push -u origin issue-${{ github.event.issue.number }} --force

      - name: Wait for branch to be available
        run: |
          sleep 10

      - name: Checkout pushed branch
        run: |
          git checkout issue-${{ github.event.issue.number }}

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: issue-${{ github.event.issue.number }}
          base: main
          title: "Fix for issue #${{ github.event.issue.number }}"
          body: "This PR addresses the issue #${{ github.event.issue.number }}."
