name: Create PR on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a new branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git checkout -b issue-${{ github.event.issue.number }}

      - name: Introduce a small edit
        run: |
          echo "# Temporary change to ensure PR creation" >> temp_change_${{ github.event.issue.number }}.md
          date >> temp_change_${{ github.event.issue.number }}.md
          git add temp_change_${{ github.event.issue.number }}.md
          git commit -m "Introduce a temporary change for issue #${{ github.event.issue.number }}"

      - name: Push branch
        run: |
          git push origin issue-${{ github.event.issue.number }}

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: issue-${{ github.event.issue.number }}
          base: main
          title: "Fix for issue #${{ github.event.issue.number }}"
          body: "This PR addresses the issue #${{ github.event.issue.number }}."
