name: Create PR on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create a new branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git checkout -b issue-${{ github.event.issue.number }}
          git pull origin main

      - name: Make a change
        run: |
          echo "Issue #${{ github.event.issue.number }} - $(date)" >> auto-pr-tracker.txt
          git add auto-pr-tracker.txt
          git commit -m "Update deployments.txt for issue #${{ github.event.issue.number }} on $(date)" || echo "No changes to commit"

      - name: Push branch
        run: |
          git push -u origin issue-${{ github.event.issue.number }} --force

      - name: Create a pull request with GitHub CLI
        run: |
          gh pr create --base main --head issue-${{ github.event.issue.number }} --title "${{ github.event.issue.title }}" --body "Fixes #${{ github.event.issue.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
