name: Create PR on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create a new branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          sanitized_title=$(echo "${{ github.event.issue.title }}" | sed 's/[^a-zA-Z0-9]/-/g')
          git checkout -b feature-${sanitized_title}
          git pull origin main

      - name: Make a change
        run: |
          sanitized_title=$(echo "${{ github.event.issue.title }}" | sed 's/[^a-zA-Z0-9]/-/g')
          echo "Issue #${sanitized_title} - $(date)" >> auto-pr-tracker.txt
          git add auto-pr-tracker.txt
          git commit -m "Update auto-pr-tracker.txt for issue #${sanitized_title} on $(date)" || echo "No changes to commit"

      - name: Push branch
        run: |
          sanitized_title=$(echo "${{ github.event.issue.title }}" | sed 's/[^a-zA-Z0-9]/-/g')
          git push -u origin feature-${sanitized_title} --force

      - name: Create a pull request with GitHub CLI
        run: |
          sanitized_title=$(echo "${{ github.event.issue.title }}" | sed 's/[^a-zA-Z0-9]/-/g')
          gh pr create --base main --head feature-${sanitized_title} --title "${{ github.event.issue.title }}" --body "Fixes #${sanitized_title}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
